title: "Lucas Lanzendorf"
description: "Lucas Lanzendorf is a CT-based engineer with a degree in Mechanical Engineering from the California Institute of Technology."
baseurl: ""
url: "https://lanzendorf.github.io"

exclude:
  - demo/
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"

theme: cvless